### ISSUE TITLE
denite ≥ 2.0 breaks current configuration settings

### ISSUE THREAD

**Issue by ipatch** [ctaylo21/jarvis#22]
Heads up to anyone who upgrades to denite ≥ 2.0 the denite settings from this repo are not compatible with denite 2.0.  From what I can tell Shougo removed the ability to add custom mappings that this dotfiles repo uses to map certain key bindings with denite, ie. 

<kbd>leader</kbd>+<kbd>t</kbd> _fuzzy file search_

#### Error Messages

```shell
[denite] pynvim.api.nvim.NvimError:
Error detected while processing function denite#helper#call_denite
```

👆 some of the error messages that I was being presented with after upgrading to denite 2.x

All that said, sifting through the open / closed issue for denite, one of the better solutions I came across was,

https://github.com/Shougo/denite.nvim/issues/646#issuecomment-498967842

**Comment by jhkersul** [comment]
Wait, have you tested after this PR https://github.com/ctaylo21/jarvis/pull/21 was merged?

**Comment by ipatch** [comment]
I have not, but after reading the PR you linked it sounds like specifying the commit hash in the PR sets denite to the version before the breaking changes were introduced, no?

**Comment by jhkersul** [comment]
Totally! I mean, your issue is still valid!
I was just wondering if you had this problem even after that PR (which would be strange, since I tested that particular version)

**Comment by ipatch** [comment]
Yup yup setting my plugin manager ie. minpac to use the commit revision you specified in your PR allows the settings I adapted from this dotfiles repo to work, ie. no error messages and what not when using denite.

I ended up coming across this repo after reading [this](https://www.freecodecamp.org/news/a-guide-to-modern-web-development-with-neo-vim-333f7efbf8e2/) article.

**Comment by ctaylo21** [comment]
Thanks for the report. Looks like there were some breaking changes made that I'll need to address.

**Comment by ctaylo21** [comment]
I'm seeing a slightly different error when I upgrade that is the same as this currently open issue: https://github.com/Shougo/denite.nvim/issues/658

**Comment by qbedard** [comment]
Looks like Shougo fixed that denite issue. Is this resolved by it?

**Comment by ctaylo21** [comment]
It's still broken, but not because of a bug. I think it's just a bunch of configuration options changed and now my mappings don't work because of breaking changes. I'm currently trying to slog through denite docs and issues to figure out what changed.

**Comment by ctaylo21** [comment]
PR open for this now. If anyone has time to check, feel free. Will likely merge today.

**Comment by ipatch** [comment]
any headway being made with issue?

**Comment by ctaylo21** [comment]
This was was fixed and merged into master on Aug 8. Let me know if it isn't working for you!
